services:
  elastic:
    build:
      context: .
      dockerfile: Dockerfile.nori        # analysis-nori 플러그인 설치된 ES
    image: custom-elasticsearch:8.17.4
    container_name: elasticcommerce-elastic-1
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health?timeout=5s | grep -q '\"status\":\"'"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    container_name: elasticcommerce-kibana-1
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    depends_on:
      - elastic


  redis:
    image: redis:7.0
    container_name: elasticcommerce-redis-1
    ports:
      - '6379:6379'
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile   # Spring Boot fat-jar 빌드용 Dockerfile
    image: elastic-commerce:latest
    container_name: elasticcommerce-app-1
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://elasticsearch.c3o8g2ymaiuh.ap-northeast-2.rds.amazonaws.com:3306/elastic_commerce?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=asdf2003
      - SPRING_ELASTICSEARCH_URIS=http://elastic:9200
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=3.39.194.194:9092
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      elastic:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  redis_data: